#!/bin/bash

# 订阅源持久化问题测试脚本

echo "================================"
echo "订阅源持久化测试"
echo "================================"
echo ""
echo "请按照以下步骤手动测试："
echo ""
echo "1️⃣  【测试重启场景】"
echo "   a. 确保你已经有订阅源（如果没有，先添加一些）"
echo "   b. 完全关闭应用"
echo "   c. 重新打开应用"
echo "   d. 打开开发者工具 (F12)"
echo "   e. 检查 Console 中的日志："
echo "      - 看到 '[FeedStore] hydrateFromCache: N feeds' 其中 N > 0"
echo "      - 看到 '[FeedStore] loadFeeds: N feeds from IPC'"
echo "   f. 观察侧边栏是否显示订阅源"
echo ""
echo "   ✅ 预期结果：订阅源应该立即显示（来自缓存）"
echo "   ❌ 如果失败：检查 localStorage 是否被清空"
echo ""
echo "2️⃣  【测试视图切换场景】"
echo "   a. 确保当前在"全部"视图，能看到订阅源"
echo "   b. 点击"视频"视图"
echo "   c. 再点击回"全部"视图"
echo "   d. 检查 Console 中的日志："
echo "      - 看到 '[UrlSync] Updating view state'"
echo "      - 不应该看到 '[FeedStore] feeds.length changed'"
echo "   e. 观察侧边栏订阅源是否还在"
echo ""
echo "   ✅ 预期结果：订阅源应该保持显示，不会消失"
echo "   ❌ 如果失败：查看是否有 'feeds.length changed' 日志及其堆栈跟踪"
echo ""
echo "3️⃣  【测试同步订阅源场景】"
echo "   a. 打开设置页面"
echo "   b. 找到"订阅源同步"部分"
echo "   c. 点击"立即同步"按钮"
echo "   d. 检查 Console 中的日志："
echo "      - 看到 '[FeedStore] loadFeeds: N feeds from IPC'"
echo "   e. 切换几次视图（全部 → 视频 → 社交 → 全部）"
echo "   f. 观察订阅源是否一直保持显示"
echo ""
echo "   ✅ 预期结果：同步后订阅源应该保持稳定，切换视图不消失"
echo "   ❌ 如果失败：记录完整的 Console 日志"
echo ""
echo "4️⃣  【测试 feeds:updated 事件】"
echo "   a. 在 Console 中执行以下命令来监听事件："
echo "      window.__feedsUpdateCount = 0"
echo "      window.api.on('feeds:updated', () => {"
echo "        window.__feedsUpdateCount++"
echo "        console.log('feeds:updated event #' + window.__feedsUpdateCount)"
echo "      })"
echo "   b. 切换视图几次"
echo "   c. 观察是否频繁触发 feeds:updated 事件"
echo ""
echo "   ✅ 预期结果：切换视图不应该触发 feeds:updated"
echo "   ❌ 如果频繁触发：可能后端有问题"
echo ""
echo "================================"
echo "如果所有测试通过，问题已修复！"
echo "如果仍有问题，请提供："
echo "  1. 完整的 Console 日志"
echo "  2. localStorage 内容（执行 debug-feeds-state.html）"
echo "  3. 失败的具体步骤"
echo "================================"
