export {
  buildDiscoverCategoryOptions,
  canonicalizeDiscoverRoute,
  DISCOVER_SUBSCRIBE_VIEW_OPTIONS,
  feedMatchesDiscoverTarget,
  findDiscoverSubscribeFeed,
  hostOfDiscoverTarget,
  normalizeDiscoverCategory,
  parseDiscoverSubscribeTarget,
  resolveDiscoverSubscribeCategory,
  resolveDiscoverSubscribeConfig,
  resolveDiscoverSubscribeTitle,
  resolveDiscoverSubscribeUrl,
  resolveDiscoverSubscribeView,
  type DiscoverSubscribeTarget,
  type ResolvedDiscoverSubscribeConfig,
} from '../../../shared/discover-target-resolution'
